# Generated by Django 4.2.4 on 2023-08-21 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '0002_alter_autores_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Original',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(max_length=255)),
                ('assunto', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('original', models.FileField(upload_to='originais/')),
                ('autores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autores.autores')),
            ],
        ),
    ]
